name: Sitemap Package Release

env:
  OUTPUT: ./Output
  CONFIG: Release

on:
  workflow_dispatch:
    inputs:
      package_version:
        description: 'Package version'
        required: true

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Get Version 
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/release\//}
      shell: bash
      
    - uses: actions/checkout@v2  
      
    - name: Setup .net core
      uses: actions/setup-dotnet@v1.4.0
      
    - name: Restore dependencies
      run: dotnet restore ./src/uSeoToolkit.Umbraco.Sitemap/uSeoToolkit.Umbraco.Sitemap.csproj
      
    - name: Restore dependencies
      run: dotnet restore ./src/uSeoToolkit.Umbraco.Sitemap.Core/uSeoToolkit.Umbraco.Sitemap.Core.csproj
      
    - name: Build
      run: dotnet build ./src/uSeoToolkit.Umbraco.Sitemap.Core/uSeoToolkit.Umbraco.Sitemap.Core.csproj --configuration ${{ env.CONFIG }} --no-restore
      
    - name: Build
      run: dotnet build ./src/uSeoToolkit.Umbraco.Sitemap/uSeoToolkit.Umbraco.Sitemap.csproj --configuration ${{ env.CONFIG }} --no-restore
      
    - name: Create NuGet package file for Core
      run: dotnet pack ./src/uSeoToolkit.Umbraco.Sitemap.Core/uSeoToolkit.Umbraco.Sitemap.Core.csproj -c ${{ env.CONFIG }} --no-build -o ${{ env.OUTPUT }} /p:version=${{ github.event.inputs.name }}
    
    - name: Create NuGet package file for Backoffice
      run: dotnet pack ./src/uSeoToolkit.Umbraco.Sitemap/uSeoToolkit.Umbraco.Sitemap.csproj -c ${{ env.CONFIG }} --no-build -o ${{ env.OUTPUT }} /p:version=${{ github.event.inputs.name }}
   
#    - name: Push packages to NuGet
#      run: dotnet nuget push "**/*.nupkg" -k ${{ secrets.NUGET_DEPLOY_KEY }} -s https://api.nuget.org/v3/index.json

    - name: upload-artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build-Results-${{ github.event.inputs.package_version }}
        path: ${{ env.OUTPUT }}/**/*
